### ISSUE TITLE
Extremely dope! Thank you for making this :)

### ISSUE THREAD

**Issue by thedonquixotic** [vanessa-luna/banner-comments-plus#2]

**Comment by thedonquixotic** [comment]
Also would be cool if someone added a unicode font version. Those are great for small comments!

**Comment by vanessa-luna** [comment]
Very sorry I didn't see this earlier.

Thanks for the comment. Other extensions that did this didn't have the customizations I wanted.

Can you explain further what you mean by a unicode font version?

**Comment by thedonquixotic** [comment]
@vanessa-luna No worries! Someone else actually already implemented the unicode thing I was talking about and it really makes more sense for their existing code base anyway. Though I recommend checking it out! https://marketplace.visualstudio.com/items?itemName=brunnerh.insert-unicode
